/****************************************************** 
FileName:T_BM_HYXXWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_BM_HYXX
{
    //=========================================================================
    //  ClassName : T_BM_HYXXContants
    /// <summary>
    /// T_BM_HYXX的常数类
    /// </summary>
    //=========================================================================
    public class T_BM_HYXXContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string HYBHFieldName = "HYBH";
        public static readonly string HYBHFieldRemark = "会员编号";
    
        public static readonly string HYXMFieldName = "HYXM";
        public static readonly string HYXMFieldRemark = "姓名";
    
        public static readonly string HYNCFieldName = "HYNC";
        public static readonly string HYNCFieldRemark = "昵称";
    
        public static readonly string HYSRFieldName = "HYSR";
        public static readonly string HYSRFieldRemark = "生日";
    
        public static readonly string HYXXFieldName = "HYXX";
        public static readonly string HYXXFieldRemark = "学校";
    
        public static readonly string HYBJFieldName = "HYBJ";
        public static readonly string HYBJFieldRemark = "班级";
    
        public static readonly string JZXMFieldName = "JZXM";
        public static readonly string JZXMFieldRemark = "家长姓名";
    
        public static readonly string JZDHFieldName = "JZDH";
        public static readonly string JZDHFieldRemark = "家长电话";
    
        public static readonly string ZCSJFieldName = "ZCSJ";
        public static readonly string ZCSJFieldRemark = "注册时间";
    
        public static readonly string ZKSSFieldName = "ZKSS";
        public static readonly string ZKSSFieldRemark = "课时总数";
    
        public static readonly string XHKSSFieldName = "XHKSS";
        public static readonly string XHKSSFieldRemark = "消耗课时";
    
        public static readonly string SYKSSFieldName = "SYKSS";
        public static readonly string SYKSSFieldRemark = "剩余课时";
        
    
        public static readonly string AutoGenerateField = "HYBH";
        public static readonly int AutoGenerateNumberLength = 8;
        public static readonly string AutoGeneratePrefix = "HY";
        public static readonly bool AllowAutoGenerateID = true;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = true;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 6;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = true;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "HYBH";
        public static readonly string TitleField = "HYXM";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
