/****************************************************** 
FileName:T_BM_KCYYXXWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_BM_KCYYXX
{
    //=========================================================================
    //  ClassName : T_BM_KCYYXXContants
    /// <summary>
    /// T_BM_KCYYXX的常数类
    /// </summary>
    //=========================================================================
    public class T_BM_KCYYXXContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string KCYYBHFieldName = "KCYYBH";
        public static readonly string KCYYBHFieldRemark = "课程预约编号";
    
        public static readonly string KCBBHFieldName = "KCBBH";
        public static readonly string KCBBHFieldRemark = "课程表编号";
    
        public static readonly string HYBHFieldName = "HYBH";
        public static readonly string HYBHFieldRemark = "会员编号";
    
        public static readonly string YYSJFieldName = "YYSJ";
        public static readonly string YYSJFieldRemark = "预约时间";
    
        public static readonly string YYBZFieldName = "YYBZ";
        public static readonly string YYBZFieldRemark = "预约备注";
    
        public static readonly string SKZTFieldName = "SKZT";
        public static readonly string SKZTFieldRemark = "上课状态";
    
        public static readonly string XHKSFieldName = "XHKS";
        public static readonly string XHKSFieldRemark = "消耗课时";
    
        public static readonly string KTZPFieldName = "KTZP";
        public static readonly string KTZPFieldRemark = "课堂照片";
    
        public static readonly string JSPJFieldName = "JSPJ";
        public static readonly string JSPJFieldRemark = "教师评价";
    
        public static readonly string PJRFieldName = "PJR";
        public static readonly string PJRFieldRemark = "评价人";
    
        public static readonly string PJSJFieldName = "PJSJ";
        public static readonly string PJSJFieldRemark = "评价时间";
        
    
        public static readonly string AutoGenerateField = "KCYYBH";
        public static readonly int AutoGenerateNumberLength = 8;
        public static readonly string AutoGeneratePrefix = "YY";
        public static readonly bool AllowAutoGenerateID = true;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = true;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 6;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = true;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "KCYYBH";
        public static readonly string TitleField = "KCBBH";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
